### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by Ashutosh876** [Ashutosh876/Mup-project_humidifier#1]
Post respective components of the temerature sensor, humudity sensor, humidifier etc

**Comment by vijayalaxmi99** [comment]
[Report.pdf](https://github.com/Ashutosh876/Mup-project_humidifier/files/1910219/Report.pdf)

**Comment by vijayalaxmi99** [comment]
[Intelligent Humidistat.zip](https://github.com/Ashutosh876/Mup-project_humidifier/files/1910237/Intelligent.Humidistat.zip)
